# Generated by Django 5.0 on 2024-02-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0002_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phonenumber',
        ),
    ]
