# Generated by Django 5.0 on 2024-02-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0003_remove_contactus_phonenumber'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='Contactus',
        ),
    ]
