# Generated by Django 5.0 on 2024-02-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0004_alter_contactus_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='comments',
            new_name='comment',
        ),
    ]
